grumphp:
  hide_circumvention_tip: true
  ascii:
    failed: ~
    succeeded: ~
  fixer:
    enabled: true
    fix_by_default: true
  environment:
    paths:
      - .env
      - .env.local
  testsuites:
    git_commit_msg:
      tasks:
        - git_commit_message
    git_pre_commit:
      tasks:
        - composer
        - git_blacklist
        - git_branch_name
        - phpcpd
        - phpcs
        - phpmd
        - phpstan
        - yamllint
    tests:
      tasks:
        - behat
        - phpunit
  tasks:
    behat:
      config: .behat.qa-drupal.yml
    composer:
      no_check_publish: true
    git_blacklist:
      keywords:
        - " die\\("
        - " exit;"
        - " exit\\("
        - "\\$_[A-Z_]+\\["
      regexp_type: E
      whitelist_patterns:
        - "#^web/(modules|themes|profiles)/custom/#"
      triggered_by:
        - php
        - inc
        - install
        - module
        - theme
        - profile
    git_branch_name:
      whitelist:
        - "#^master|develop|feature/([A-Z][A-Z0-9]+-\\d+|[a-z][a-z0-9]*(-[a-z0-9]+)*)|(release|hotfix)/\\d+(\\.\\d+){2}$#"
    git_commit_message:
      enforce_no_subject_trailing_period: false
      max_body_width: 80
      max_subject_width: 80
      matchers:
        - "/^([A-Z][A-Z0-9]+-\\d+(, [A-Z][A-Z0-9]+-\\d+)*: )?(Add|Change|Fix|Update|Remove) /"
      case_insensitive: false
    phpcpd:
      directory:
        - web
      exclude:
        - web/core
        - web/libraries
        - web/*/contrib
        - web/modules/custom/*/tests
        - web/sites
      min_lines: 10
      triggered_by:
        - php
        - inc
        - install
        - module
        - theme
        - profile
    phpcs:
      standard:
        - .phpcs.qa-drupal.xml
      report_width: 120
      whitelist_patterns:
        - "#^web/(modules|themes|profiles)/custom/#"
      ignore_patterns:
        - node_modules/
      triggered_by:
        - php
        - inc
        - install
        - module
        - theme
        - profile
        - yml
    phpmd:
      ruleset:
        - .phpmd.qa-drupal.xml
      whitelist_patterns:
        - "#^web/(modules|themes|profiles)/custom/#"
      triggered_by:
        - php
        - inc
        - install
        - module
        - theme
        - profile
    phpstan:
      configuration: .phpstan.qa-drupal.neon
      force_patterns:
        - "#^web/(modules|themes|profiles)/custom/((?:(?!tests)[^/])+/)+[^/]+$#"
      ignore_patterns:
        - "#.*#"
      triggered_by:
        - php
        - inc
        - install
        - module
        - theme
        - profile
    phpunit:
      config_file: .phpunit.qa-drupal.xml
    yamllint:
      whitelist_patterns:
        - "#^(\\.[^/]+/)?[^/]+\\.yml$#"
        - "#^config/#"
        - "#^web/(modules|themes|profiles)/custom/#"
      ignore_patterns:
        - node_modules/

services:
  listener.qa_drupal.task:
    class: Digipolisgent\QA\Drupal\GrumPHP\EventListener\TaskEventListener
    tags:
      - { name: grumphp.event_listener, event: grumphp.task.run, method: createTaskConfig, priority: 100 }
      - { name: grumphp.event_listener, event: grumphp.task.complete, method: removeTaskConfig }
      - { name: grumphp.event_listener, event: grumphp.task.failed, method: removeTaskConfig }
