grumphp:
  hooks_dir: ~
  hooks_preset: local
  stop_on_failure: false
  process_timeout: 3600
  hide_circumvention_tip: true
  ascii:
    failed: ~
    succeeded: ~
  fixer:
    enabled: true
    fix_by_default: true
  environment:
    paths:
      - .env
      - .env.local
  testsuites:
    git_commit_msg:
      tasks:
        - git_commit_message
    git_pre_commit:
      tasks:
        - composer
        - git_blacklist
        - git_branch_name
        - phpcpd
        - phpcs
        - phpmd
        - phpstan
        - yamllint
    tests:
      tasks:
        - behat
        - phpunit
  tasks:
    behat:
      config: qa-drupal.behat.yml
    composer:
      no_check_publish: true
    git_blacklist:
      keywords:
        - " die\\("
        - " exit;"
        - " exit\\("
        - "\\$_[A-Z_]+\\["
      regexp_type: E
      whitelist_patterns:
        - "#^web/(modules|themes|profiles)/custom/#"
      triggered_by:
        - inc
        - install
        - module
        - php
        - profile
        - theme
    git_branch_name:
      whitelist:
        - "#^master|develop|feature/([A-Z][A-Z0-9]+-\\d+|[a-z][a-z0-9]*(-[a-z0-9]+)*)|(release|hotfix)/\\d+(\\.\\d+){2}$#"
    git_commit_message:
      matchers:
        - "/^([A-Z][A-Z0-9]+-\\d+(, [A-Z][A-Z0-9]+-\\d+)*: )?(Add|Change|Fix|Update|Remove|Refactor) /"
      case_insensitive: false
    phpcpd:
      directory:
        - web
      exclude:
        - web/core
        - web/libraries
        - web/*/contrib
        - web/modules/custom/*/tests
        - web/sites
        - "*.api.php"
        - "*Test.php"
        - "*TestBase.php"
        - "*TestCase.php"
      min_lines: 10
      triggered_by:
        - inc
        - install
        - module
        - php
        - profile
        - theme
    phpcs:
      standard:
        - phpcs.qa-drupal.xml
      report_width: 120
      whitelist_patterns:
        - "#^web/(modules|themes|profiles)/custom/#"
      ignore_patterns:
        - build/
        - node_modules/
        - sassdocs/
        - "*.md"
      triggered_by:
        - css
        - inc
        - install
        - js
        - module
        - php
        - profile
        - theme
        - twig
        - yml
    phpmd:
      ruleset:
        - phpmd.qa-drupal.xml
      whitelist_patterns:
        - "#^web/(modules|themes|profiles)/custom/#"
      triggered_by:
        - inc
        - install
        - module
        - php
        - profile
        - theme
    phpstan:
      configuration: phpstan.qa-drupal.neon
      level: 4
      force_patterns:
        - "#^web/(modules|themes|profiles)/custom/((?:(?!tests)[^/])+/)+[^/]+$#"
      ignore_patterns:
        - "#.*#"
      triggered_by:
        - inc
        - install
        - module
        - php
        - profile
        - theme
    phpunit:
      config_file: phpunit.qa-drupal.xml
    yamllint:
      whitelist_patterns:
        - "#^(\\.[^/]+/)?[^/]+\\.yml$#"
        - "#^config/#"
        - "#^web/(modules|themes|profiles)/custom/#"
      ignore_patterns:
        - node_modules/

services:
  listener.qa_drupal.task:
    class: Digipolisgent\QA\Drupal\GrumPHP\EventListener\TaskEventListener
    tags:
      - { name: grumphp.event_listener, event: grumphp.task.run, method: createTaskConfig, priority: 100 }
