parameters:
  hooks_dir: ~
  hooks_preset: local
  stop_on_failure: true
  hide_circumvention_tip: true
  ascii: ~
  tasks:
    phpstan:
      configuration: vendor/digipolisgent/qa-drupal/configs/phpstan-extension-d9.neon
      triggered_by:
        - php
        - inc
        - install
        - module
        - theme
        - profile
